# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------


# -----------------------------
# Ajouter le repo au Python Path
# -----------------------------
from config.config import *

print (f"VOLUME_SOURCE_PATH = {VOLUME_SOURCE_PATH}")
print (f"BRONZE_METADATA = {BRONZE_METADATA}")


# COMMAND ----------

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {BRONZE_ZONE}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {SILVER_ZONE}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {GOLD_SCHEMA}")


# COMMAND ----------

df = spark.sql(f'select * from {BRONZE_ZONE}.taxi_landing_drivers_incremental')
df.schema

# COMMAND ----------

VALID_RULES_OR_FAIL = {
   "customers" : 
        {
        "valid_customer_id" : "CAST(customer_id as bigint)  IS NOT NULL"
        },
    "drivers" : 
        {
        "valid_driver_id"   : "CAST(driver_id as bigint) IS NOT NULL"
        },
     "locations" : 
        {
        "valid_location_id" : "CAST(location_id as bigint) IS NOT NULL"
        },
     "payments" :
        {
        "valid_payment_id"  : "CAST(payment_id as bigint) IS NOT NULL",
        "valid_customer_id" : "CAST(customer_id as bigint) IS NOT NULL",
        "valid_trip_id"     : "CAST(trip_id as bigint) IS NOT NULL"
        },
    "trips" :
        {
        "valid_trip_id"     : "CAST(trip_id as bigint) IS NOT NULL",
        "valid_customer_id" : "CAST(customer_id as bigint) IS NOT NULL",
        "valid_driver_id"   : "CAST(driver_id as bigint) IS NOT NULL",
        "valid_vehicule_id" : "CAST(vehicule_id as bigint) IS NOT NULL"
        },
    "vehicules" :
        {
        "valid_vehicule_id" : "CAST(vehicule_id as bigint) IS NOT NULL"
        }

}

VALID_RULES_OR_DROP = {

    "customers" : 
        {
        # "valid_customer_id" : "CAST(customer_id as bigint)  IS NOT NULL",
        "vaild_first_name"  : "first_name IS NOT NULL",
        "valid_last_name"   : "last_name IS NOT NULL",
        "valid_email":         r"email IS NOT NULL AND email RLIKE '^[a-zA-Z0-9][a-zA-Z0-9._-]*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z]{2,}$'",
        "valid_phone":         "phone_number IS NOT NULL",
        "valid_city" :         "city IS NOT NULL",
        "signup_date" :        "CAST(signup_date as date) IS NOT NULL",
        "last_updated_timestamp": "CAST(last_updated_timestamp as timestamp) IS NOT NULL",
        "new_data_rescued_data" : "_rescued_data IS NULL",
        },
    "drivers" : 
        {
        # "valid_driver_id"   : "CAST(driver_id as bigint) IS NOT NULL",
        "vaild_first_name"  : "first_name IS NOT NULL",
        "valid_last_name"   : "last_name IS NOT NULL",
        "valid_phone":        "phone_number IS NOT NULL",
        "valid_vehicule_id" : "CAST(vehicule_id as int) IS NOT NULL",
        "valid_driver_rating" : "CAST(driver_rating as double) IS NOT NULL",
        "valid_city" :        "city IS NOT NULL",
        "last_updated_timestamp": "CAST(last_updated_timestamp as timestamp) IS NOT NULL",
        "new_data_rescued_data" : "_rescued_data IS NULL",
        },
    "locations" : 
        {
        # "valid_location_id" : "CAST(location_id as bigint) IS NOT NULL",
        "valid_city" : "city IS NOT NULL",
        "valid_state" : "state IS NOT NULL",
        "valid_country" : "country IS NOT NULL",
        "valid_latitude" : "CAST(latitude as double) IS NOT NULL",
        "valid_longitude" : "CAST(longitude as double) IS NOT NULL",
        "last_updated_timestamp": "CAST(last_updated_timestamp as timestamp) IS NOT NULL",
        "new_data_rescued_data" : "_rescued_data IS NULL",          
        },
    "payments" :
        {
        # "valid_payment_id"  : "CAST(payment_id as bigint) IS NOT NULL",
        # "valid_customer_id" : "CAST(customer_id as bigint) IS NOT NULL",
        # "valid_trip_id"     : "CAST(trip_id as bigint) IS NOT NULL",
        "valid_payment_method" : "payment_method IS NOT NULL",
        "valid_payment_status" : "payment_status IS NOT NULL",
        "valid_payment_amount" : "CAST(amount as double) IS NOT NULL",
        "valid_transaction_time" : "CAST(transaction_time as timestamp) IS NOT NULL",
        "last_updated_timestamp": "CAST(last_updated_timestamp as timestamp) IS NOT NULL",
        "new_data_rescued_data" : "_rescued_data IS NULL",
        },
    "trips" :
        {
        # "valid_trip_id"     : "CAST(trip_id as bigint) IS NOT NULL",
        # "valid_customer_id" : "CAST(customer_id as bigint) IS NOT NULL",
        # "valid_driver_id"   : "CAST(driver_id as bigint) IS NOT NULL",
        # "valid_vehicule_id" : "CAST(vehicule_id as bigint) IS NOT NULL",
        "valid_trip_start_time" : "CAST(trip_start_time as timestamp) IS NOT NULL",
        "valid_trip_end_time" : "CAST(trip_end_time as timestamp) IS NOT NULL",
        "vaild_trip_start_location" : "start_location IS NOT NULL", 
        "vaild_trip_end_location" : "end_location IS NOT NULL",
        "valid_trip_distance_km" : "CAST(distance_km as double) IS NOT NULL",
        "valid_fare_amount" : "CAST(fare_amount as double) IS NOT NULL",
        "valid_payment_method" : "payment_method IS NOT NULL",
        "valid_trip_status" : "trip_status IS NOT NULL",
        "last_updated_timestamp": "CAST(last_updated_timestamp as timestamp) IS NOT NULL",
        "new_data_rescued_data" : "_rescued_data IS NULL"
        },
    "vehicules" :
        {
        # "valid_vehicule_id" : "CAST(vehicule_id as bigint) IS NOT NULL",
        "vaild_license_plate" : "license_plate IS NOT NULL",
        "valid_year" : "CAST(year as int) IS NOT NULL",
        "valid_vehicule_type" : "vehicule_type IS NOT NULL",
        "last_updated_timestamp": "CAST(last_updated_timestamp as timestamp) IS NOT NULL",
        "new_data_rescued_data" : "_rescued_data IS NULL"
        }
        
}



    
            
