# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------


# -----------------------------
# Ajouter le repo au Python Path
# -----------------------------
from config.config import *

print (f"VOLUME_SOURCE_PATH = {VOLUME_SOURCE_PATH}")
print (f"BRONZE_METADATA = {BRONZE_METADATA}")


# COMMAND ----------

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {BRONZE_ZONE}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {SILVER_ZONE}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {GOLD_SCHEMA}")

