# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------


# -----------------------------
# Ajouter le repo au Python Path
# -----------------------------
from config.config import *

print (f"VOLUME_SOURCE_PATH = {VOLUME_SOURCE_PATH}")
print (f"BRONZE_METADATA = {BRONZE_METADATA}")


# COMMAND ----------

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {BRONZE_ZONE}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {SILVER_ZONE}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {GOLD_SCHEMA}")


# COMMAND ----------

df = spark.sql(f'select * from {BRONZE_ZONE}.taxi_landing_drivers_incremental')
df.schema

# COMMAND ----------

df = spark.sql(f"select * from {BRONZE_ZONE}.taxi_bronze_customers_ingestion_cleaned")
display(df.count())

def delete_duplicates(df : DataFrame,dedup_cols:List, cdc_table : str):
    df = df.withColumn("dedupkey", concat(*dedup_cols))
    df = df.withColumn("dedupCount", row_number().over(Window.partitionBy("dedupkey").orderBy(desc(cdc_table))))
    df = df.filter(col("dedupCount") == 1).orderBy("dedupkey")
    df = df.drop("dedupkey", "dedupCount")
    
    return df
    
df = delete_duplicates(df,['customer_id'],"last_updated_timestamp")
df = df.withColumn('phone_number', regexp_replace(col('phone_number'), r'[^0-9]', ''))
df = df.withColumn('email', regexp_replace(col('email'), r'[^a-zA-Z0-9@.]', ''))
df = df.withColumn('domain', regexp_replace(col('email'), r'^.*@', ''))
df = df.withColumn('full_name',concat_ws(' ',col('first_name'),col('last_name')))

display(df)


# COMMAND ----------

df = spark.sql(f"select * from {BRONZE_ZONE}.taxi_bronze_payments_ingestion_cleaned")
display(df.count())

def delete_duplicates(df : DataFrame,dedup_cols:List, cdc_table : str):
    df = df.withColumn("dedupkey", concat(*dedup_cols))
    df = df.withColumn("dedupCount", row_number().over(Window.partitionBy("dedupkey").orderBy(desc(cdc_table))))
    df = df.filter(col("dedupCount") == 1).orderBy("dedupkey")
    df = df.drop("dedupkey", "dedupCount")
    
    return df

def get_duplicates(df: DataFrame, column_names: list) -> DataFrame:
   """
   Retourne les lignes dupliquées basées sur une liste de colonnes.
   Inclut toutes les occurrences des doublons.
   """
   # 1. Compter les occurrences pour chaque groupe de colonnes
   duplicate_counts = df.groupBy(column_names).count().filter("count > 1")
   # 2. Joindre avec le DataFrame original pour récupérer toutes les colonnes
   # On utilise un 'inner join' pour ne garder que ce qui est dans duplicate_counts
   duplicates = df.join(
       duplicate_counts.select(column_names),
       on=column_names,
       how="inner"
   )
   return duplicates

df = get_duplicates(df,['trip_id','customer_id'])
df.orderBy("trip_id","payment_id").display()




# df = delete_duplicates(df,['trip_id','customer_id'],"last_updated_timestamp")
# df = df.withColumn('payment_status_final', 
#                     when( ((col("payment_method") == "CARD") & (col("payment_status") == "SUCCESS")),"ONLINE_SUCCESS")
#                     .when( ((col("payment_method") == "CARD") & (col("payment_status") == "FAILED")),"ONLINE_FAILED")
#                     .when( ((col("payment_method") == "CARD") & (col("payment_status") == "PENDING")),"ONLINE_PENDING")
#                     .when( ((col("payment_method") != "CARD") & (col("payment_status") == "SUCCESS")),"OFFLINE_SUCCESS")
#                     .when( ((col("payment_method") != "CARD") & (col("payment_status") == "FAILED")),"OFFLINE_FAILED")
#                     .when( ((col("payment_method") != "CARD") & (col("payment_status") == "PENDING")),"ONLINE_PENDING")
#                     .otherwise("INVALID")
#                     )
# df = df.withColumn('amount', floor(col('amount'),2))
# df = df.withColumn('modified_at',current_timestamp())

# display(df)

# COMMAND ----------

df = spark.sql(f"select * from {BRONZE_ZONE}.taxi_bronze_trips_ingestion_cleaned")
df = delete_duplicates(df,['trip_id','customer_id','driver_id','vehicle_id'],"last_updated_timestamp")

df = get_duplicates(df,['trip_id','customer_id','driver_id','vehicle_id'])
df.orderBy("customer_id","driver_id","vehicle_id").display()

# df = df.withColumn('payyment_type', when(col("payment_method") == "WALLET", "online").otherwise("physical"))
# df = df.withColumn('modified_at',current_timestamp())




# COMMAND ----------

entites = {
           "trips"     : "Historic of Trip Taxi cleaned",
           "vehicules" : "List of Vehicles cleaned",
           "payments"  : "Historic of Payment cleaned",
           "locations" : "Localisation of Taxi cleaned",
           "drivers"   : "Drivers cleaned",
           "customers" : "Customers Cleaned" 
           }

for i in entites:
    df = spark.sql(f"drop table {SILVER_ZONE}.taxi_silver_{i}")
    
